---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 172.31.0.21:3260
    iqn: iqn.2023-03.net.opequon:jellyfin-config
    lun: 0
    initiatorName: iqn.2023-03.net.opequon:openshift
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-music
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  capacity:
    storage: 1Ti 
  accessModes:
    - ReadWriteMany 
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /export/jellyfin/music
    server: galadriel.private.opequon.net
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: jellyfin-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Mi
  volumeName: jellyfin-music
